a = input('Digite algo: ')
print(f'O tipo  primitivo de {a} é:', type(a))
print('Somente espaços?', a.isspace())
print('É um numero?', a.isnumeric())
print('É um alfabético?', a.isalpha())
print('É um alfanumérico?', a.isalnum())
print('Está em letras maiúsculas?', a.isupper())
print('Está em letras minúsculas?', a.islower())
print('Está capitalizada', a.istitle())
